### ISSUE TITLE
Is `TIAAS_EMAIL` used for anything?

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/tiaas2#43]
https://github.com/galaxyproject/tiaas2/blob/e0a12ae02e79127aa3579c553be43e8d926bb77a/config/local_settings.py.template#L40

I can't find a reference to this anywhere in the codebase?

**Comment by hexylena** [comment]
```
training/templates/training/register.html
31:{{ settings.TIAAS_EMAIL }}. Thanks a lot!
63:You can contact us at <a href="mailto:{{ settings.TIAAS_EMAIL }}">{{ settings.TIAAS_EMAIL }}</a>
```

**Comment by neoformit** [comment]
Ahh OK my bad, I deleted this from the templates! Thanks.
