### ISSUE TITLE
Registration email HTML as text

### ISSUE THREAD

**Issue by neoformit** [galaxyproject/tiaas2#46]
Registration email notifications seem to be formatted incorrectly:

https://github.com/galaxyproject/tiaas2/blob/e0a12ae02e79127aa3579c553be43e8d926bb77a/training/views.py#L47

HTML email content should be added as a multipart alternative. Instead, this email is send with `Content-type: text/plain` and we end up with this:

![image](https://user-images.githubusercontent.com/42562517/194202545-554bab10-e999-41ad-8c39-e2e9e4c56365.png)

As this just goes to admins I'd suggest just formatting as text:

```py
send_mail(
    f"New TIaaS Request ({identifier})",
    (
        "A new TIaaS request has been received. View it in the admin dashboard: "
        f"{settings.GALAXY_URL}/tiaas/admin/training/training/?processed__exact=UN"
    ),
```
 
As in: https://github.com/neoformit/tiaas2/commit/d7c0a6b4ccfc7fcc5d7d43b4d5be6f1c1a602e79

If you're happy with this, I'll add this to my PR! (Coming soon, I promise)

**Comment by hexylena** [comment]
Yes, text only is fine, please add it :+1:
