### ISSUE TITLE
Timely deletion of contact info not guaranteed; may cause other issues

### ISSUE THREAD

**Issue by jdavcs** [galaxyproject/tiaas2#6]
Deletion of contact info (re: GDPR) is contingent on someone accessing the Django admin training page that displays a list of all training records. This does not guarantee the timely deletion of contact info (contrary to text in registration form): if the admin page is not accessed, the info is not deleted. Furthermore, the deletion happens as an unexpected side effect of an unrelated action (accessing an admin page). 

Also, given that the date fields are currently not validated (which will be addressed separately), it is easy for someone to submit a request for training, mistakenly selecting an end date that is > 60 days in the past. In this case, there will be no way to contact them to correct the mistake, as the contact info will be wiped out upon accessing the admin page.

One simple solution is a custom Django management task + a cron job.

**Comment by hexylena** [comment]
I considered a cron job but at the time wanted something simple and no one looked at the DB (and it wasn't backed up for a long time) so it seemed sufficient given that we checked the page basically daily for new trainings.

Definitely would be an improvement.

**Comment by hexylena** [comment]
Should be fixed as of the addition of the cron job everyone is running by default to cleanup the roles.
